### ISSUE TITLE
AudioException: Audio device error encountered. - Error Code: 0x2 ???

### ISSUE THREAD

**Issue by BlackPhlox** [joshcampbell191/EBG.Xrm.AzureDevOpsTasks#4]
Yeah, this is a weird error 😅
![image](https://user-images.githubusercontent.com/25123512/186629906-53524d5c-77a7-4edd-a58f-5f37515c7d29.png)

**Comment by BlackPhlox** [comment]
```
##[debug]CrmSvcUtil : CRM Service Utility [Version 9.1.0.93]
##[debug]© 2020 Microsoft Corporation. All rights reserved
##[debug]
##[debug]Begin Reading Metadata
##[debug]Completed Reading Metadata 00:01:12.3065076
##[debug]Begin Writing File
##[debug] Ensuring Context File is Accessible  -  Ensuring Context File is Accessible 
##[debug] Writing file Actions.cs to C:\Users\VssAdministrator\AppData\Local\Temp\tmp3B7F.tmp  -  Writing file Actions.cs to C:\Users\VssAdministrator\AppData\Local\Temp\tmp3B7F.tmp 
##[debug]Processing 288 OptionSets
##[debug]Wrote 0 OptionSets
##[debug]Processing 1052 Entities
##[debug]Wrote 0 Entities
##[debug]Processing 1183 Messages
##[debug]Wrote 750 Messages
##[debug]Code written to C:\Users\VssAdministrator\AppData\Local\Temp\tmp3B7F.tmp.
##[debug] Updating File D:\a\1\s\SCT\Actions\Actions.cs  -  Updating File D:\a\1\s\SCT\Actions\Actions.cs 
##[debug] Cleaning up Temporary File C:\Users\VssAdministrator\AppData\Local\Temp\tmp3B7F.tmp  -  Cleaning up Temporary File C:\Users\VssAdministrator\AppData\Local\Temp\tmp3B7F.tmp 
##[debug] C:\Users\VssAdministrator\AppData\Local\Temp\tmp3B7F.tmp Moved To: D:\a\1\s\SCT\Actions\Actions.cs  -  C:\Users\VssAdministrator\AppData\Local\Temp\tmp3B7F.tmp Moved To: D:\a\1\s\SCT\Actions\Actions.cs 
##[debug]Completed Writing File 00:00:01.0018417
##[debug]Error - System.Speech.Internal.Synthesis.AudioException: Audio device error encountered. - Error Code: 0x2
##[debug]   at System.Speech.Internal.Synthesis.VoiceSynthesis.Speak(Prompt prompt)
##[debug]   at DLaB.EarlyBoundGenerator.Logic.Speak(String words, Boolean speakResult)
##[debug]   at DLaB.EarlyBoundGenerator.Logic.HandleResult(String filePath, DateTime date, CreationType creationType, String consoleOutput, Boolean speakResult)
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Invoke-EarlyBoundGenerator : Exception has been thrown by the target of an invocation.
##[debug]At C:\hostedtoolcache\windows\EBGTools\1.0.0\EBGXrm\1.0.0\InvokeEarlyBoundGenerator.ps1:36 char:1
##[debug]+ Invoke-EarlyBoundGenerator -ConnectionString $CrmConnectionString -Se ...
##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : NotSpecified: (:) [Invoke-EarlyBoundGenerator], TargetInvocationException
##[debug]    + FullyQualifiedErrorId : System.Reflection.TargetInvocationException,EBG.Xrm.PowerShell.Cmdlets.InvokeEarlyBoundG    eneratorCommand
##[debug] 
##[debug]Script stack trace:
##[debug]at <ScriptBlock>, C:\hostedtoolcache\windows\EBGTools\1.0.0\EBGXrm\1.0.0\InvokeEarlyBoundGenerator.ps1: line 36
##[debug]at <ScriptBlock>, D:\a\_tasks\EBGEarlyBoundGenerator_8d09ef8e-4e82-4802-af33-6d094ad1b6f4\1.0.0\EBGEarlyBoundGenerator.ps1: line 30
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Speech.Internal.Synthesis.AudioException: Audio device error encountered. - Error Code: 0x2
##[debug]   at System.Speech.Internal.Synthesis.VoiceSynthesis.Speak(Prompt prompt)
##[debug]   at DLaB.EarlyBoundGenerator.Logic.Speak(String words, Boolean speakResult)
##[debug]   at DLaB.EarlyBoundGenerator.Logic.HandleResult(String filePath, DateTime date, CreationType creationType, String consoleOutput, Boolean speakResult)
##[debug]   at DLaB.EarlyBoundGenerator.Logic.Create(CreationType creationType)
##[debug]   --- End of inner exception stack trace ---
##[debug]   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
##[debug]   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
##[debug]   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
##[debug]   at EBG.Xrm.PowerShell.Cmdlets.InvokeEarlyBoundGeneratorCommand.CreateActions(Object logic)
##[debug]   at EBG.Xrm.PowerShell.Cmdlets.InvokeEarlyBoundGeneratorCommand.ExecuteAll(Object logic)
##[debug]   at EBG.Xrm.PowerShell.Cmdlets.InvokeEarlyBoundGeneratorCommand.ProcessRecord()
##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
##[error]Exception has been thrown by the target of an invocation.
##[debug]Processed: ##vso[task.logissue type=error]Exception has been thrown by the target of an invocation.
##[debug]Processed: ##vso[task.complete result=Failed]
```

**Comment by BlackPhlox** [comment]
Is there a way to disable the text-to-speech dependency for DLaB.EarlyBoundGenerator?

**Comment by BlackPhlox** [comment]
Yep, there was: https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/issues/207
